pr: none
trigger:
  batch: false
  branches:
    include:
    - main
  paths:
    include:
    - ArmTemplates/Infrastructure/*

jobs:
- job: DeployARMTemplate
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  
  - task: PowerShell@2
    displayName: 'Deploy ARM Template'
    inputs:
      targetType: 'inline'
      script: |
        # Run 'az login' to authenticate with Azure
        az login --service-principal --username $(servicePrincipalId) --password $(servicePrincipalKey) --tenant $(tenantId) --allow-no-subscriptions
                
        # Set Azure Subscription
        $subscriptionId = "$(SubscriptionId)"
        az account set --subscription $subscriptionId
                
        # Set Resource Group and Location
        $resourceGroupName = "Accruent-Assessment-RG"
        $location = "westeurope"
        
        Write-Host "Creating Resource Group..."
        az group create --name $resourceGroupName --location $location
        
        Write-Host "Deploying ARM Template..."
        $deploymentName = "AccruentDeployment"
        $templateFile = "$(System.DefaultWorkingDirectory)/ArmTemplates/Infrastructure/template.json"
        $parameterFile = "$(System.DefaultWorkingDirectory)/ArmTemplates/Infrastructure/parameters.json"
        
        az deployment group create `
          --resource-group $resourceGroupName `
          --name $deploymentName `
          --template-file $templateFile `
          --parameters $parameterFile

