parameters:
- name: name
  displayName: Job Name
  type: string
  default: Publish_Directory
- name: displayName
  displayName: Job Display Name
  type: string
  default: Publish Directory
- name: dependsOn
  displayName: Depends On
  type: object
  default: ''
- name: condition
  displayName: Condition
  type: string
  default: ''
- name: variables
  displayName: Variables
  type: object
  default: ''
- name: vmImage
  displayName: Variables
  type: string
  default: ubuntu-latest
- name: validateJsonFilesTaskName
  displayName: Validate Json Files Task Name
  type: string
  default: Validate JSON Files
- name: validateJsonFiles
  displayName: List of JSON File (can include wildcards)
  type: string
  default: ''
- name: artefactSourceFolder
  displayName: Artefact Source Folder
  type: string
- name: artefactName
  displayName: Artefact Name
  type: string

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  ${{ if not(eq(parameters.dependsOn, '')) }}:
    dependsOn: ${{ parameters.dependsOn }}
  ${{ if not(eq(parameters.condition, '')) }}:
    condition: ${{ parameters.condition }}
  ${{ if not(eq(parameters.variables, '')) }}:
    variables: ${{ parameters.variables }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: PowerShell@2
    condition: not(eq('${{ parameters.validateJsonFiles }}', ''))
    displayName: ${{ parameters.validateJsonFilesTaskName }}
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Testing JSON files -"
        foreach ($line in "${{ parameters.validateJsonFiles }}".Trim().Split("`n"))
        {
            $filesToGet = ("{0}/{1}" -f (Resolve-Path -Path "${{ parameters.artefactSourceFolder }}"), $line)
            Get-ChildItem -File -Path $filesToGet | ForEach-Object { 
                Write-Host (" -- {0}" -f $_.FullName)
                Get-Content -Raw -Path $_.FullName | Test-Json | Out-Null
            }
        }
      pwsh: true
  - publish: ${{ parameters.artefactSourceFolder }}
    artifact: ${{ parameters.artefactName }}