pr: none
trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    include:
    - AzureDeploy/ArmTemplates/Infrastructure/*
    
variables:
- template: ../Templates/Variables/variables--pipeline--global.yml

parameters:
- name: copyStages
  type: object
  default:
  - name: BVT_UK_South
    displayName: BVT - UK South
    variables:
    - template: ../Variables/variables--infrastructure--global.yml
    - template: ../Variables/variables--infrastructure--bvt.yml

name: $(major).$(minor).$(patch)$(branch)

stages:

### Publish artefacts.
- template: ../Templates/Stages/stage--publish-artefacts.yml
  parameters:
    name: Publish_Artefacts
    displayName: Publish Artefacts
    variables:
    - template: ../Variables/variables--infrastructure--global.yml
    artefacts:
    - armTemplates

### Deploy to BVT.
- ${{ each stage in parameters.copyStages }}:
  - template: ../Templates/Stages/stage--infrastructure--deploy.yml
    parameters:
      name: Deploy_${{ stage.name }}
      displayName: Deploy ${{ stage.displayName }}
      dependsOn: Publish_Artefacts
      variables: ${{ stage.variables }}
      environment: BVT